-- 1. Create Table
create table public.likes (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id       uuid references public.users(id) not null,
  box_shadow_id bigint references public.box_shadows(id) not null
);
comment on table public.likes is 'Each like on the box shadows.';

-- Secure the table
alter table public.likes enable row level security;

create policy "Allow anon-key full access"
  on public.likes for all using (
    auth.role() = 'anon'
  );

create policy "Allow individual insert access"
  on public.likes for insert with check (
    auth.uid() = user_id
  );

create policy "Allow individual update access"
  on public.likes for update using (
    auth.uid() = user_id
  );

create policy "Allow individual delete access"
  on public.likes for delete using (
    auth.uid() = user_id
  );

-- Send "previous data" on change
alter table public.likes replica identity full;
