/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  '/box_shadow': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.box_shadow.id']
          /** User's ID */
          user?: parameters['rowFilter.box_shadow.user']
          /** Box Shadow values */
          boxShadow?: parameters['rowFilter.box_shadow.boxShadow']
          /** Theme mode */
          theme?: parameters['rowFilter.box_shadow.theme']
          /** Element's shape */
          shape?: parameters['rowFilter.box_shadow.shape']
          /** Name of the design */
          name?: parameters['rowFilter.box_shadow.name']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: definitions['box_shadow'][]
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** box_shadow */
          box_shadow?: definitions['box_shadow']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.box_shadow.id']
          /** User's ID */
          user?: parameters['rowFilter.box_shadow.user']
          /** Box Shadow values */
          boxShadow?: parameters['rowFilter.box_shadow.boxShadow']
          /** Theme mode */
          theme?: parameters['rowFilter.box_shadow.theme']
          /** Element's shape */
          shape?: parameters['rowFilter.box_shadow.shape']
          /** Name of the design */
          name?: parameters['rowFilter.box_shadow.name']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.box_shadow.id']
          /** User's ID */
          user?: parameters['rowFilter.box_shadow.user']
          /** Box Shadow values */
          boxShadow?: parameters['rowFilter.box_shadow.boxShadow']
          /** Theme mode */
          theme?: parameters['rowFilter.box_shadow.theme']
          /** Element's shape */
          shape?: parameters['rowFilter.box_shadow.shape']
          /** Name of the design */
          name?: parameters['rowFilter.box_shadow.name']
        }
        body: {
          /** box_shadow */
          box_shadow?: definitions['box_shadow']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
}

export interface definitions {
  box_shadow: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    /** User's ID */
    user?: string
    /** Box Shadow values */
    boxShadow?: string
    /** Theme mode */
    theme?: string
    /** Element's shape */
    shape?: string
    /** Name of the design */
    name?: string
  }
}

export interface parameters {
  /** Preference */
  preferParams: 'params=single-object'
  /** Preference */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
  /** Preference */
  preferCount: 'count=none'
  /** Filtering Columns */
  select: string
  /** On Conflict */
  on_conflict: string
  /** Ordering */
  order: string
  /** Limiting and Pagination */
  range: string
  /** Limiting and Pagination */
  rangeUnit: string
  /** Limiting and Pagination */
  offset: string
  /** Limiting and Pagination */
  limit: string
  /** box_shadow */
  'body.box_shadow': definitions['box_shadow']
  'rowFilter.box_shadow.id': string
  /** User's ID */
  'rowFilter.box_shadow.user': string
  /** Box Shadow values */
  'rowFilter.box_shadow.boxShadow': string
  /** Theme mode */
  'rowFilter.box_shadow.theme': string
  /** Element's shape */
  'rowFilter.box_shadow.shape': string
  /** Name of the design */
  'rowFilter.box_shadow.name': string
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface operations {}
